// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://efbdtnfdijvsyrntstik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVmYmR0bmZkaWp2c3lybnRzdGlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNDI3ODksImV4cCI6MjA2MDYxODc4OX0.2s_5mZVnxBeycMIqYwMDhqF_WkYQOoZdwL3cRX7FuOo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);